sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_3_3.gemfile
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

rvm:
  - 2.4.3
  - 2.3.1
  - 2.2.7

addons:
  postgresql: 9.4
  code_climate:
    repo_token: 7ca9964050acd0a0fbedb864033493bb31c166b170bb034246b714b46419c605

before_install:
   - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  exclude:
    - rvm: 2.2.7
      gemfile: gemfiles/spree_master.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/spree_master.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/spree_master.gemfile
